from .models import Song


SONGS = [
    Song(id="night-drive", title="Night Drive", artist="Chromatics", genre="synthpop", moods=["dreamy", "moody", "nostalgic"], contexts=["night drive", "late night"], bpm=92, year=2007, description="cinematic neon synths, hushed vocals, and a hypnotic nocturnal pulse", accent="#8b7cff"),
    Song(id="holocene", title="Holocene", artist="Bon Iver", genre="indie folk", moods=["reflective", "calm", "bittersweet"], contexts=["rainy day", "quiet morning", "study"], bpm=74, year=2011, description="delicate acoustic textures and reflective lyrics with an expansive wintry atmosphere", accent="#d09a6a"),
    Song(id="sunset-lover", title="Sunset Lover", artist="Petit Biscuit", genre="electronic", moods=["dreamy", "calm", "hopeful"], contexts=["sunset", "study", "travel"], bpm=91, year=2015, description="soft electronic percussion and glowing melodic layers made for unhurried moments", accent="#f0a36c"),
    Song(id="space-song", title="Space Song", artist="Beach House", genre="dream pop", moods=["dreamy", "melancholic", "nostalgic"], contexts=["late night", "rainy day", "stargazing"], bpm=81, year=2015, description="weightless synths, slow-burning drums, and yearning vocals in a cosmic haze", accent="#6870c9"),
    Song(id="pink-white", title="Pink + White", artist="Frank Ocean", genre="alternative r&b", moods=["warm", "nostalgic", "calm"], contexts=["sunset", "slow morning", "travel"], bpm=78, year=2016, description="sunlit harmonies and elegant soul production carrying tender memories", accent="#e7a1a4"),
    Song(id="alaska", title="Alaska", artist="Maggie Rogers", genre="indie pop", moods=["uplifting", "fresh", "free"], contexts=["morning", "walking", "road trip"], bpm=104, year=2016, description="organic percussion and buoyant electronic pop about movement and renewal", accent="#61af93"),
    Song(id="motion-sickness", title="Motion Sickness", artist="Phoebe Bridgers", genre="indie rock", moods=["bittersweet", "wry", "cathartic"], contexts=["road trip", "singalong"], bpm=108, year=2017, description="bright guitar motion contrasts sharp, emotionally candid storytelling", accent="#d5a2bd"),
    Song(id="midnight-city", title="Midnight City", artist="M83", genre="synthpop", moods=["energetic", "nostalgic", "euphoric"], contexts=["night drive", "party", "running"], bpm=105, year=2011, description="towering synth hooks and restless momentum evoke a glowing city after dark", accent="#4c79d8"),
    Song(id="garden-song", title="Garden Song", artist="Phoebe Bridgers", genre="indie folk", moods=["dreamy", "reflective", "uneasy"], contexts=["late night", "rainy day"], bpm=73, year=2020, description="muted folk textures and surreal images unfold like a half-remembered dream", accent="#789b86"),
    Song(id="clearest-blue", title="Clearest Blue", artist="CHVRCHES", genre="synthpop", moods=["euphoric", "energetic", "hopeful"], contexts=["workout", "party", "night drive"], bpm=120, year=2015, description="patient electronic build erupts into a bright, exhilarating synth release", accent="#4fa5d8"),
    Song(id="heartbeats", title="Heartbeats", artist="José González", genre="acoustic", moods=["intimate", "calm", "bittersweet"], contexts=["quiet morning", "rainy day", "reading"], bpm=88, year=2003, description="fingerpicked acoustic guitar transforms longing into something gentle and close", accent="#b98a5f"),
    Song(id="everything-in-its-right-place", title="Everything In Its Right Place", artist="Radiohead", genre="art rock", moods=["hypnotic", "uneasy", "focused"], contexts=["study", "late night", "coding"], bpm=124, year=2000, description="looped keys and fractured vocals create precise, immersive concentration", accent="#7b8b76"),
    Song(id="ribs", title="Ribs", artist="Lorde", genre="alternative pop", moods=["nostalgic", "anxious", "euphoric"], contexts=["late night", "singalong", "party"], bpm=128, year=2013, description="pulsing minimal pop captures the thrill and fear of growing older", accent="#977ac0"),
    Song(id="mykonos", title="Mykonos", artist="Fleet Foxes", genre="indie folk", moods=["warm", "adventurous", "reflective"], contexts=["road trip", "travel", "hiking"], bpm=94, year=2008, description="layered folk harmonies and driving acoustic rhythm open onto wide landscapes", accent="#d08363"),
    Song(id="intro", title="Intro", artist="The xx", genre="indie electronic", moods=["moody", "focused", "cinematic"], contexts=["study", "night drive", "coding"], bpm=100, year=2009, description="spare guitar figures and deep electronic rhythm create cool, wordless focus", accent="#85878d"),
    Song(id="dog-days", title="Dog Days Are Over", artist="Florence + The Machine", genre="indie pop", moods=["joyful", "euphoric", "free"], contexts=["running", "celebration", "road trip"], bpm=150, year=2008, description="handclaps, harp, and soaring vocals build into an ecstatic rush of release", accent="#d45c5c"),
    Song(id="apocalypse", title="Apocalypse", artist="Cigarettes After Sex", genre="dream pop", moods=["romantic", "melancholic", "dreamy"], contexts=["late night", "rainy day"], bpm=94, year=2017, description="reverberant guitars and whispered vocals drift through romantic melancholy", accent="#777a83"),
    Song(id="weightless", title="Weightless", artist="Marconi Union", genre="ambient", moods=["calm", "focused", "serene"], contexts=["study", "meditation", "sleep"], bpm=60, year=2011, description="slow ambient swells and soft pulses create an uncluttered space for deep calm", accent="#68a2a5"),
]
